# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=todo_app
    volumes:
      - mongodb_data_todo_app:/data/db

volumes:
  mongodb_data_todo_app:
