name: Build and deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        name: checkout repository
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: documentation/package-lock.json
      - run: npm ci
        name: npm ci
        working-directory: documentation
      - run: npm run deploy
        name: npm run deploy
        working-directory: documentation
      - name: Disable Jekyll
        run: touch documentation/out/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: documentation/out
          commit-message: "chore: deploy latest docs"